### ISSUE TITLE
It does nothing...

### ISSUE THREAD

**Issue by fr2632** [MoonshineSG/Octoprint-Filament#30]
When filament is running out, my sensor just beeps and I get error "abnormal sensor" on the LCD. The extruder keeps going without pause.

**Comment by MoonshineSG** [comment]
i'm not sure how the LCD comes in the picture. The plugin does not handle any LCD display. That sounds more like the firmware reading the sensor not the octoprint ....

Are you sure the plugin is configured correctly ?

**Comment by fr2632** [comment]
It just have been a coincidence that the error appears, however the print does not pause and thats the main issue. How do you configure the plugin ?

**Comment by MoonshineSG** [comment]
it's all in the plugin description. please read it.

**Comment by fr2632** [comment]
I did but the description is talking about GPIO on the raspberry, my filament sensor is connected to the mainboard of the printer and not to the raspberry.

**Comment by MoonshineSG** [comment]
then the plugin is not for you.  
the sensor would have to be handled by the firmware..
