### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by MarcusWolschon** [MoonshineSG/Octoprint-Filament#4]
I'd like to write a plugin based on this one but you didn't include any license definition.
So I don't know what I can do an what license I can choose for my modified code.

**Comment by MoonshineSG** [comment]
If it's commercial product I take 10%... Kidding! 
It's AGPLv3 (see http://plugins.octoprint.org/plugins/filament_sensor/)

**Comment by MarcusWolschon** [comment]
found it hidden in setpup.py .
We should add it to README.md
