### ISSUE TITLE
Question: will this work for prints not started by Octoprint?

### ISSUE THREAD

**Issue by colinodell** [MoonshineSG/Octoprint-Filament#5]
Sometimes I use the SD card and LCD control panel to print objects instead of starting the print through Octoprint.  Will this plugin work in that situation?  Or does it only work if I start the print process from Octoprint?

I have a Flashforge Creator Pro if that matters.

**Comment by MoonshineSG** [comment]
No, that will not work. Or at least I don't think it would. You can always try and let me know :) 
I don't print from SD and I don't have an LCD... in my opinion, neither are needed once you have OctoPrint

**Comment by colinodell** [comment]
Ah okay.  I think I'm ultimately going to go with a hardware sensor wired directly into my FFCP.  Thanks for the answer!
