### ISSUE TITLE
Plugin Settings for config.yaml

### ISSUE THREAD

**Issue by kylek29** [MoonshineSG/Octoprint-Filament#6]
Not sure if this was just a fluke on my build.

Instructions state to place:

```
octoprint_filament:
   pin: XX
   bounce: 400
```

Into the config.yaml, but these won't load. The plugin is initialized as "filament". I got it to load with:

```
filament:
   pin: XX
   bounce: 400
```

**Comment by MoonshineSG** [comment]
You are right. It was a mistake in the readme file.
