### ISSUE TITLE
API location no API key found

### ISSUE THREAD

**Issue by brotherchris** [MoonshineSG/Octoprint-Filament#7]
When I try to access the API location /plugin/filament/status. I only get the message. No API key provided. How would you provide it the octoprint key?

**Comment by MoonshineSG** [comment]
See http://docs.octoprint.org/en/master/api/general.html

**Comment by brotherchris** [comment]
Sorry, I guess I don't get how it works. Thanks for the reply, I will try to figure it out.

**Comment by MoonshineSG** [comment]
The plugin will pause the print when the filament runs out. The additional API is provided and it can be called from other plugins which might need to know the status of the filament. It would be called as described in the above mentioned document.

> The API key must be supplied in the custom HTTP header X-Api-Key, e.g.
> 
> GET /plugin/filament/status HTTP/1.1
> Host: example.com
> X-Api-Key: abcdef...

(A better implementation would be an event base trigger with a subscription model, but thats a different story.)
